framework: qunit

load_paths:
  - test/src
  - src
  - polyfills

logical_paths:
  - polyfills.js
  - test.js

ci:
  plugins:
    sauce:
      browsers:
        - name: "Google Chrome"
          platforms: ["Mac", "Windows"]
        - name: "Safari"
          platforms: ["Mac"]
        - name: "Firefox"
          platforms: ["Mac", "Windows"]
        - name: "Internet Explorer"
          platforms: ["Windows"]
