load_paths:
  - test/src
  - test/blade_runner_assets
  - src
  - polyfills

logical_paths:
  - polyfills.js
  - test.js

plugins:
  sauce_labs:
    browsers:
      chrome:
        platform: ["Mac", "Windows"]
      safari:
        platform: ["Mac"]
      firefox:
        platform: ["Mac", "Windows"]
      ie:
        platform: ["Windows"]
