load_paths:
  - test/src
  - src
  - polyfills

logical_paths:
  - polyfills.js
  - test.js

plugins:
  sauce_labs:
    browsers:
      chrome:
        os: Mac, Windows
      safari:
        platform: Mac
      firefox:
        platform: Mac, Windows
      ie:
